#!/bin/bash
echo "[*] Hardening Linux..."
sudo apt update && apt upgrade -y
sudo ufw enable
sudo ufw allow 2222/tcp
sudo systemctl disable --now cups bluetooth
sudo apt install rkhunter lynis -y
sudo rkhunter --update && rkhunter --check
sudo lynis audit system
